openapi: 3.0.0
info:
  title: TL;DR websites
  version: 1.0.0
servers:
- url: /
security:
- JWTSessionCookie: []
tags:
- description: 'Endpoints for summarizing input. '
  name: summarize
- description: Endpoints for retrieving the user's profile and stored summaries.
  name: user
- description: Endpoints for handling authentication and user creation.
  name: auth
paths:
  /user:
    get:
      operationId: userGET
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      summary: Returns information and stored summaries for current user.
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
  /user/summaries:
    get:
      operationId: userSummariesGET
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Summary'
                type: array
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      summary: Returns list of summaries for current user.
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
  /user/summaries/{id}:
    get:
      operationId: userSummariesIdGET
      parameters:
      - description: UUID for saved Summary
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
          description: Summarized text
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      summary: Return summary with given id.
      tags:
      - user
      x-eov-operation-handler: controllers/UserController
  /login:
    post:
      description: Given `id_token` from Google Sign In, verify token and authenticate
        user. If authentication is successful, set a JWT to establish user session.
      operationId: loginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: User ID to retreive information for
        required: true
      responses:
        "303":
          content:
            application/jwt:
              schema:
                format: jwt
                type: string
          description: Redirect to home page. Sends the JWT in both the payload and
            Set-Cookie header.
          headers:
            Location:
              explode: false
              schema:
                description: Redirect URL
                type: string
              style: simple
            Set-Cookie:
              explode: false
              schema:
                example: token=some.jwt.token; Path=/; HttpOnly;
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      security: []
      summary: Log in user. New users will be signed up then logged in.
      tags:
      - auth
      x-eov-operation-handler: controllers/AuthController
  /logout:
    get:
      operationId: logoutGET
      responses:
        "204":
          description: Invalidate session cookie.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      security: []
      summary: Log out user by invalidating JWT.
      tags:
      - auth
      x-eov-operation-handler: controllers/AuthController
  /csrf-token:
    get:
      operationId: csrf_tokenGET
      responses:
        "200":
          description: Set anti-CSRF cookie.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Wrapper for generic error response that displays the error
            code and error message.
      security: []
      summary: Get anti-CSRF token. Use on app startup.
      tags:
      - auth
      x-eov-operation-handler: controllers/AuthController
  /summarize:
    post:
      operationId: summarizePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizeRequest'
        description: Input text or the URL of webpage to be summarized.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
          description: Summarized text
      summary: Call DeepAI to summarize raw text or a webpage. Summary is saved under
        user's profile.
      tags:
      - summarize
      x-eov-operation-handler: controllers/SummarizeController
  /feed:
    get:
      operationId: feedGET
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Summary'
                type: array
          description: OK
      security: []
      summary: Returns list of all publicly viewable summaries.
      tags:
      - feed
      x-eov-operation-handler: controllers/FeedController
components:
  responses:
    Summary:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Summary'
      description: Summarized text
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Wrapper for generic error response that displays the error code
        and error message.
  schemas:
    User:
      example:
        name: name
        summaries:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          plaintext: plaintext
          summarizedText: summarizedText
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userId: userId
          url: url
        - createdAt: 2000-01-23T04:56:07.000+00:00
          isPublic: true
          plaintext: plaintext
          summarizedText: summarizedText
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          userId: userId
          url: url
      properties:
        name:
          type: string
        summaries:
          items:
            $ref: '#/components/schemas/Summary'
          type: array
      required:
      - name
      type: object
    LoginRequest:
      example:
        clientType: web
        id_token: xxxxx.yyyyy.zzzzz
      properties:
        id_token:
          description: id_token, as returned by `googleUser.getAuthResponse().id_token`
          example: xxxxx.yyyyy.zzzzz
          type: string
        clientType:
          description: client type, either 'web' OR 'ios'.
          enum:
          - web
          - ios
          example: web
          type: string
      required:
      - clientType
      - id_token
      type: object
    SummarizeRequest:
      description: Request can contain either plaintext or a webpage URL, but not
        both.
      oneOf:
      - $ref: '#/components/schemas/SummarizeRequest_oneOf'
      - $ref: '#/components/schemas/SummarizeRequest_oneOf_1'
    Summary:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        isPublic: true
        plaintext: plaintext
        summarizedText: summarizedText
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        userId: userId
        url: url
      properties:
        id:
          format: uuid
          type: string
        userId:
          type: string
        plaintext:
          description: Original text that was summarized.
          type: string
        url:
          description: URL of webpage that was summarized.
          type: string
        summarizedText:
          type: string
        createdAt:
          description: Time summary was first requested.
          format: date-time
          type: string
        isPublic:
          description: Whether the summary appears on the global summaries feed.
          type: boolean
      required:
      - createdAt
      - id
      - summarizedText
      - userId
      type: object
    Error:
      example:
        code: 0
        message: message
      properties:
        code:
          description: Error code.
          format: int32
          type: integer
        message:
          description: Error message.
          type: string
      required:
      - code
      - message
      type: object
    SummarizeRequest_oneOf:
      example:
        url: https://en.wikipedia.org/wiki/Mars_Climate_Orbiter
        isPublic: true
      properties:
        url:
          format: uri
          type: string
        isPublic:
          description: Whether the summary appears on the global summaries feed.
          type: boolean
      required:
      - isPublic
      - url
      type: object
    SummarizeRequest_oneOf_1:
      example:
        plaintext: |
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis nulla malesuada, vulputate ex in, vestibulum ligula. Sed consequat erat tincidunt urna consequat euismod. Praesent vel leo faucibus, ullamcorper augue quis, eleifend mi. Phasellus vitae mauris fermentum, dapibus augue a, rutrum libero. Nulla vitae malesuada ante. Ut euismod tellus auctor massa congue, et feugiat enim ornare. Nulla mi felis, tristique eu enim et, condimentum porttitor urna. Aliquam erat volutpat. Aliquam erat volutpat. Etiam vitae elit ac lectus feugiat tempus. Nunc porttitor sit amet nisi eget tristique. Donec sit amet tortor erat. Fusce eu metus ex. Mauris sit amet justo sit amet dui fringilla eleifend. Duis accumsan velit eros, non imperdiet nibh viverra nec. Etiam congue iaculis massa eleifend condimentum. Suspendisse potenti. Morbi hendrerit vestibulum leo quis ornare. Proin vel vehicula est. Aliquam non vehicula arcu. Etiam eleifend pharetra justo, et dignissim dui pharetra nec. Pellentesque gravida tincidunt feugiat. Nunc sodales id arcu a dapibus. Nunc eget libero consectetur, dignissim dolorullamcorper, tempor ipsum. Nunc blandit justo eu eros porttitor tempor. Quisque sed leo venenatis, posuere leo sit amet, commodo tortor."
        isPublic: false
      properties:
        plaintext:
          type: string
        isPublic:
          description: Whether the summary appears on the global summaries feed.
          type: boolean
      required:
      - isPublic
      - plaintext
      type: object
  securitySchemes:
    JWTSessionCookie:
      description: JWT session cookie. Set after user logs in with Google Sign in
        and is verified by the /login endpoint.
      in: cookie
      name: token
      type: apiKey
