openapi: '3.0.0'
info:
  title: TL;DR websites
  version: '1.0.0'
# USAGE: To regenerate boilerplate code, make sure openapi-generator-cli is installed, then from the ./server directory, 
#        run  $openapi-generator-cli generate -g nodejs-express-server -o . -i .\openapi.yaml
#        Note that existing files WILL be overwritten; you will need to manually revert changes to those.

paths:
  /user:
    get:
      tags: 
        - user
      summary: Returns information and stored summaries for current user.
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          $ref: '#/components/responses/Error'
  /user/summaries:
    get:
      tags:
      - user
      summary: Returns list of summaries for current user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Summary'
        default:
          $ref: '#/components/responses/Error'
  /user/summaries/{id}:
    get:
      tags:
      - user
      parameters:
        - name: id
          in: path
          description: UUID for saved Summary
          required: true
          schema:
            type: string
            format: uuid
      summary: Return summary with given id.
      responses:
        '200':
          $ref: '#/components/responses/Summary'
        default:
          $ref: '#/components/responses/Error'
  /login:
    post:
      tags:
      - auth
      summary: Log in user. New users will be signed up then logged in.
      description: Given `id_token` from Google Sign In, verify token and authenticate user. If authentication is successful, set a JWT to establish user session.
      requestBody:
        description: User ID to retreive information for
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '303':
          description: Redirect to home page. Sends the JWT in both the payload and Set-Cookie header.
          headers:
            Location:
              schema:
                description: Redirect URL
                type: string
            Set-Cookie:
              schema:
                type: string
                example: token=some.jwt.token; Path=/; HttpOnly; 
          content:
            application/jwt:
              schema:
                type: string
                format: jwt
        default:
          $ref: '#/components/responses/Error'
      security: []
  /logout:
    get:
      tags:
      - auth
      summary: Log out user by invalidating JWT.
      responses:
        '204':
          description: Invalidate session cookie.
        default:
          $ref: '#/components/responses/Error'
      security: []
  /csrf-token:
    get:
      tags:
      - auth
      summary: Get anti-CSRF token. Use on app startup.
      responses:
        '200':
          description: Set anti-CSRF cookie.
        default:
          $ref: '#/components/responses/Error'
      security: []
  /summarize:
    post:
      tags:
      - summarize
      summary: Call DeepAI to summarize raw text or a webpage. Summary is saved under user's profile.
      requestBody:
        description: Input text or the URL of webpage to be summarized.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizeRequest'
      responses:
        '200':
          $ref: '#/components/responses/Summary'
  /feed:
    get:
      tags:
      - feed
      summary: Returns list of all publicly viewable summaries.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feed'
      security: []
components:
  securitySchemes:
    JWTSessionCookie:
      type: apiKey
      description: JWT session cookie. Set after user logs in with Google Sign in and is verified by the /login endpoint.
      name: token
      in: cookie
  responses:
    Summary:
      description: Summarized text
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Summary'
    Error:
      description: Wrapper for generic error response that displays the error code and error message.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    User:
      type: object
      required: 
        - name
        # summaries are optional, in case we need to query the current user without their summaries
      properties:
        name:
          type: string
        summaries:
          type: array
          items:
            $ref: '#/components/schemas/Summary'
    LoginRequest:
      type: object
      required:
      - id_token
      - clientType
      properties:
        id_token:
          description: id_token, as returned by `googleUser.getAuthResponse().id_token`
          type: string
          example: 'xxxxx.yyyyy.zzzzz'
        clientType:
          description: client type, either 'web' OR 'ios'.
          type: string
          example: 'web'
          enum:
            - web
            - ios
    SummarizeRequest:
      description: Request can contain either plaintext or a webpage URL, but not both.
      oneOf:
        - type: object
          required:
            - url
            - isPublic
          properties:
            url:
              type: string
              format: uri
            isPublic:
              type: boolean
              description: Whether the summary appears on the global summaries feed.
          example:
            url: 'https://en.wikipedia.org/wiki/Mars_Climate_Orbiter'
            isPublic: true
        - type: object
          required:
            - plaintext
            - isPublic
          properties:
            plaintext:
              type: string
            isPublic:
              type: boolean
              description: Whether the summary appears on the global summaries feed.
          example:
            plaintext: >
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis nulla malesuada, vulputate ex in, vestibulum ligula. Sed consequat erat tincidunt urna consequat euismod. Praesent vel leo faucibus, ullamcorper augue quis, eleifend mi. Phasellus vitae mauris fermentum, dapibus augue a, rutrum libero. Nulla vitae malesuada ante. Ut euismod tellus auctor massa congue, et feugiat enim ornare. Nulla mi felis, tristique eu enim et, condimentum porttitor urna. Aliquam erat volutpat. Aliquam erat volutpat. Etiam vitae elit ac lectus feugiat tempus.
              Nunc porttitor sit amet nisi eget tristique. Donec sit amet tortor erat. Fusce eu metus ex. Mauris sit amet justo sit amet dui fringilla eleifend. Duis accumsan velit eros, non imperdiet nibh viverra nec. Etiam congue iaculis massa eleifend condimentum. Suspendisse potenti.
              Morbi hendrerit vestibulum leo quis ornare. Proin vel vehicula est. Aliquam non vehicula arcu. Etiam eleifend pharetra justo, et dignissim dui pharetra nec. Pellentesque gravida tincidunt feugiat. Nunc sodales id arcu a dapibus. Nunc eget libero consectetur, dignissim dolorullamcorper, tempor ipsum. Nunc blandit justo eu eros porttitor tempor. Quisque sed leo venenatis, posuere leo sit amet, commodo tortor."
            isPublic: false
    Summary:
      type: object
      required:
        - id
        - userId
        - summarizedText
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        userId:
          # unique Google user ID returned by Google Sign In. subject to change.
          type: string
        # if /summarize is called
        plaintext:
          description: Original text that was summarized.
          type: string
        # if /summarizeByURL is called
        url:
          description: URL of webpage that was summarized.
          type: string
        summarizedText:
          type: string
        createdAt:
          description: Time summary was first requested.
          type: string
          format: date-time
        isPublic:
          description: Whether the summary appears on the global summaries feed.
          type: boolean
    Feed:
      type: object
      required:
        - summary
        - user
      properties:
        summary:
          $ref: '#/components/schemas/Summary'
        user:
          $ref: '#/components/schemas/User'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: Error code.
          type: integer
          format: int32
        message:
          description: Error message.
          type: string
security:
  - JWTSessionCookie: []
tags:
  - name: 'summarize'
    description: "Endpoints for summarizing input. "
  - name: 'user'
    description: "Endpoints for retrieving the user's profile and stored summaries."
  - name: 'auth'
    description: "Endpoints for handling authentication and user creation."